### PR TITLE
No need to create the shim since we have run `tlmgr path add`

### LINKED ISSUE #4: Should we make tinytex R package compatible with those packages ?
I found that there are some incompatibilities with R package functions. 

For example, see https://github.com/cderv/r-bucket/issues/3

* `tinytex_root()` won't work with either choco and scoop due to the way their shims are working. 

All functions that use this `tinytex_root()` won't work. 

@yihui Should we make them compatible ? Either by changing the packages, or tweaking **tinytex** ? 

I am not sure are they are mainly for use with installation from **tinytex** R package itself but that seems to be disturbing for users that they don't work. And it seems easy to detect scoop or choco because we know where they install things.

### PR DESCRIPTION
**Pull request by yihui**
See https://github.com/cderv/r-bucket/issues/3#issuecomment-695214666

Closes #4.

### CODE REVIEW

**Comment by yihui** [comment]
@naveen521kk From the logs at https://ci.appveyor.com/project/yihui/tinytex-releases/builds/35292174/job/49o4mb6lcsm4ij24, it seems `tlmgr path add` didn't succeed. The `PATH` was not changed.

**Review by naveen521kk — APPROVED** [review]
Possibly I think a shim for tlmgr is lot recommended. Because, if there is say any other anonymous tlmgr.exe` it causes issues for people. Because `exe` files have higher priority then `bat` files then commes `cmd`(possibly we can remove it from scoop. I didn't expect it does so.). Next comes the path variable, chocolatey bin folder is kept at first in adminstrative path so we are damn sure the `tlmgr` is correct one called. If you are not worried about what I told leave it. Possibly, I am going to create a thread in mailing list for making `tlmgr` to an exe file using chocolatey's shimgen. But that's ot the point here. I will approve this for now.

> it seems tlmgr path add didn't succeed. The PATH was not changed.

Idk how to do that in appveyor but it works on my computer when installed from choco ;-). You would need to do this.

**Comment by naveen521kk** [comment]
Possibly updating on next release would be good.

**Comment by yihui** [comment]
A patch version has been uploaded automatically: https://ci.appveyor.com/project/yihui/tinytex-releases/builds/35296654/job/r17xqh4pyx37j95b#L74

**Comment by naveen521kk** [comment]
I just checked my email now. 👍🏽 nice.

**Comment by naveen521kk** [comment]
@yihui Does the automatic build working? It 1 October right? We plan to publish new release each month at starting right?

**Comment by yihui** [comment]
It does. The cron job runs on Friday nights to create a release each month, so hopefully in 48 hours a new release will be created.

**Comment by naveen521kk** [comment]
Looks like we should do a release today or users can't use `tlmgr` without upgrading it.
https://tug.org/texlive/tlmgr-news.html
Better to release one today. ;-)

**Comment by cderv** [comment]
Currently I think R package **tinytex** will update `tlmgr` if necessary. Like in `tlmgr_install` function. 

@naveen521kk do you suggest there is a release each time tlmgr does one release ?

**Comment by naveen521kk** [comment]
> do you suggest there is a release each time tlmgr does one release ?

It's not like that but this should be documented somewhere. Or our install script should be updating it automatically. Maybe of that is possible I will do a PR on that.

**Comment by cderv** [comment]
> Or our install script should be updating it automatically. 

Yes I have a working branch for scoop installer that does that. It run `tlmgr update --self` after installation. Not yet finished though so not available yet.

**Comment by naveen521kk** [comment]
I will do that to chocolatey also ;-)

**Comment by yihui** [comment]
That'll be great (I mean running `tlmgr update --self` after installation).

In the R package, I will try `tlmgr update --self` if `tlmgr install` fails (often because `tlmgr` needs to be updated): https://github.com/yihui/tinytex/blob/f988323903aff51c666fa0ad1034f182ef8c7e9e/R/tlmgr.R#L106-L109

**Comment by naveen521kk** [comment]
@yihui Can you fix daily appveyor build of TinyTex? I think it is broken and manim needs it at the start of the month to avoid failing CI.

**Comment by yihui** [comment]
The daily build is, as its name indicates, built daily. If it's currently broken, I guess the build happened right before the TeX Live team updated tlmgr. Anyway, I can easier trigger a rebuild, and will do that in a minute.

**Comment by naveen521kk** [comment]
> Anyway, I can easier trigger a rebuild, and will do that in a minute.

I pinged you on that. ;-)

**Comment by naveen521kk** [comment]
Does pushing on other branch appveyor won't work? I need to test it. I added that line and need to check it. @yihui

**Comment by yihui** [comment]
> Does pushing on other branch appveyor won't work?

https://yihui.org/tinytex/TinyTeX.zip points the latest build of the repo `yihui/tinytex`, of which you don't have write permission so cannot create a branch there. If you do have write permission, the aforementioned URL will point to the latest successful build of any branch in the repo.

I just realized that I had a problem in the R package **tinyex**, and will actually need to wait for perhaps another day. Time will cure it soon :)

**Pull request merged**
